name: '{{ options.projectName }}'
description: A starter Vulcan project
version: 0.2.0
semantic-model:
  folderPath: mdls
  filePaths:
    # - input: xxx.mdl
    #  output: xxx.json
template:
  provider: LocalFile
  # Path to .sql files
  folderPath: outputs
  codeLoader: InMemory
artifact:
  provider: LocalFile
  serializer: JSON
  # Path to build result
  filePath: outputs/result.json
schema-parser:
  reader: LocalFile
  # Path to .yaml files
  folderPath: outputs
document-generator:
  specs:
    - oas3
types:
  - RESTFUL
auth:
  enabled: false
enforce-https:
  enabled: false
response-format:
  enabled: true
  options:
    default: json
    formats:
      - json
      - csv
